### ISSUE TITLE
GamessQ 1.2.1 not working under MacOS 10.12.6 Sierra

### ISSUE THREAD

**Issue by gdeslong** [brettbode/GamessQ#14] opened 2017-11-17 19:17 UTC
GamessQ 1.2.1 reports "error" when submitting job. Everything worked fine under MacOS 10.11 El Capitan.
GAMESS works fine from my terminal so I know GAMESS itself is working fine.

**Comment by brettbode** [comment] 2020-04-22 00:53
Hello,
   The problem is most likely that your spool directory path has a space (or other non-ASCII character) in it. Unfortunately the gms script does not like spaces in the variables. At some point the default app support data directory under WX or OS X must have changed to ~/Library/Application Support/ at which point the default location was broken. 

I am adding code to detect the path issue force a change of preference to the next release.

**Comment by brettbode** [comment] 2020-04-26 15:07
This is fixed in v1.2.2 that is now posted.

**Closed as completed by brettbode** 2020-04-26 15:07 UTC
Labels: bug
